workflows:
  main:
    name: Build and Deploy

    scripts:
      # Instalação de dependências
      - name: Install dependencies
        script: |
          yarn install

      # Build para Android
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleRelease -quiet

      # Testes
      - name: Run tests
        script: |
          yarn test

      # Gerar APK de distribuição
      - name: Generate APK
        script: |
          cd android
         # ./gradlew assembleRelease -quiet

    artifacts:
      # Arquivos a serem salvos como artefatos
      - app-release.apk
      - Mobile.Dev.ipa

    publishing:
      # Publicação dos artefatos gerados
      email:
        recipients:
          - your-email@example.com
