workflows:
  main:
    name: Build and Deploy

    scripts:
      # Instalação de dependências
      - name: Install dependencies
        script: |
          yarn install

      # Build para Android
      - name: Build Android
        script: |
          cd app

      # Gerar APK de distribuição
      - name: Generate APK
        script: |
          cd app
         # ./gradlew assembleRelease -quiet

    artifacts:
      # Arquivos a serem salvos como artefatos
      - app-release.apk
      - app.ipa

    publishing:
      # Publicação dos artefatos gerados
      email:
        recipients:
          - your-email@example.com
